### ISSUE TITLE
Update Page META Data

### ISSUE THREAD

**Issue by faradayadmin** [faradayafrica/Faraday-event#19]
Using this guide; https://www.npmjs.com/package/react-meta-tags

Define meta tags for the homepage and on an event page. 
If you want to work on this, indicate and the meta data will be provided to you.

**Comment by devgenix** [comment]
> Can you assign to me i do it.

Yes, I'll assign it to you now.

**Comment by devgenix** [comment]
I'll also provide you with the information needed.

**Comment by devgenix** [comment]
@Siddharth9890 

Meta Title = Events at Faraday
Meta Desciption = Discover events with faraday happening around you.
Meta image = [here](https://drive.google.com/file/d/1L-g0zks-wQawYchfdfSPYYw4Ew5vF5kC/view?usp=sharing)
Meta link = https://events.faraday.africa

Let me know if you have any other suggestions or need any other thing.

**Comment by Siddharth9890** [comment]
Sure i start working on it

**Comment by Siddharth9890** [comment]
Please review the latest pr @faradayadmin

**Comment by devgenix** [comment]
@Siddharth9890 I'm sorry, I couldn't be here. 

I've now merged the PR. Thank you so much for your contribution.
