### ISSUE TITLE
Bug: empty space (" ") is accepted as name when register for an event

### ISSUE THREAD

**Issue by ABHISHEK-PANDEY2** [faradayafrica/Faraday-event#23]
Empty spaces are accepted when we register for an event ,
we can register with only providing a space in the name input

If you can approve , i would like to work on it

**Comment by nworiekingslee** [comment]
Go ahead @ABHISHEK-PANDEY2. I have assigned you to this issue.
Also, thanks for pointing that out

**Comment by ABHISHEK-PANDEY2** [comment]
@nworiekingslee I have worked on the issue , how can i git it you for review ?  should i raise a PR directly ?
![image](https://user-images.githubusercontent.com/95560057/193628026-1efaf570-b77f-4ba5-9383-31648bcdac0f.png)

**Comment by devgenix** [comment]
This issue closed by #24
