### ISSUE TITLE
Provide feedback when there are no upcoming events

### ISSUE THREAD

**Issue by devgenix** [faradayafrica/Faraday-event#25]
See the problem [here](https://drive.google.com/file/d/1Y4hRIHSflssXn7Ww1n44w2aNjhkLX0Xi/view?usp=sharing) 

Fix: when there are no upcoming events, display a jumbotron to indicate that there are no upcoming events. You have full creative freedom. 

Here are our Brand Color codes; 
Black: #29313D
Green: #05B843
Brown: #E7CEAB
White: #E5E5E5

**Comment by racky7** [comment]
@devgenix I want to work on this. Please assign it to me.

**Comment by devgenix** [comment]
> @devgenix I want to work on this. Please assign it to me.

Sure, go ahead.

**Comment by racky7** [comment]
![Screenshot 2022-10-04 3 30 55 PM](https://user-images.githubusercontent.com/74532684/193792207-2da8ac27-f44e-44b0-be9c-378df8e6b793.png)
Is it okay?

**Comment by devgenix** [comment]
> ![Screenshot 2022-10-04 3 30 55 PM](https://user-images.githubusercontent.com/74532684/193792207-2da8ac27-f44e-44b0-be9c-378df8e6b793.png) Is it okay?

It's very okay, thank you.

**Comment by devgenix** [comment]
@racky7 create a PR for this and add me to review it.

**Comment by racky7** [comment]
I made PR, please review.

**Comment by devgenix** [comment]
> I made PR, please review.

I've left a review, please check.

**Comment by racky7** [comment]
I made the required changes and opened a new PR from a new branch. Ignore the previous one. Please review.

**Comment by devgenix** [comment]
Closed by #28
