### ISSUE TITLE
> @devgenix can I be assigned to work on that?

### ISSUE THREAD

**Issue by devgenix** [faradayafrica/Faraday-event#33]
> @devgenix can I be assigned to work on that?

Yes please.

Instead of the current look, instead contain the link in a button that opens in another tab when clicked.

The button color should be the brand green. 

_Originally posted by @devgenix in https://github.com/faradayafrica/Faraday-event/pull/32#issuecomment-1920290523_

**Comment by devgenix** [comment]
@Bluebberies

**Comment by Bluebberies** [comment]
Noted.
Will hop on it at day break

**Comment by devgenix** [comment]
Closed via #34

**Comment by devgenix** [comment]
Closed via #34
